
  CREATE TABLE "WEBLEARNING"."GRADE_SUBJECT" 
   (	"GRADEID" NUMBER, 
	"SUBJECTID" NUMBER, 
	 CONSTRAINT "FK_GRADEID_ON_GRADE" FOREIGN KEY ("GRADEID")
	  REFERENCES "WEBLEARNING"."GRADE" ("GRADEID") ENABLE, 
	 CONSTRAINT "FK_SUBJECTID_ON_SUBJECT" FOREIGN KEY ("SUBJECTID")
	  REFERENCES "WEBLEARNING"."SUBJECT" ("SUBJECTID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
